name: Tests

on: [push, pull_request]

jobs:
  build-tests:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: ${{ matrix.php }}
          tools: "composer:v2"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: composer update --no-interaction --no-progress --no-suggest

      - name: "Run tests"
        run: ./vendor/bin/phpunit Tasks/Tests/
